apiVersion: apps/v1
kind: Deployment
metadata:
  name: lne-posts-deployment
  labels:
    app: lne-posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lne-posts
  template:
    metadata:
      labels:
        app: lne-posts
    spec:
      containers:
      - name: lne-posts
        image: nouvelle0epoch/posts
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lne-posts
  name: lne-posts
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    app: lne-posts