apiVersion: apps/v1
kind: Deployment
metadata:
  name: lne-front-deployment
  labels:
    app: lne-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lne-front
  template:
    metadata:
      labels:
        app: lne-front
    spec:
      containers:
      - name: lne-front
        image: nouvelle0epoch/lne-front
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lne-front
  name: lne-front
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    app: lne-front